/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FVS6rEjFjSX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useMemo } from "react"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"

export function shop() {
  const [filters, setFilters] = useState({
    category: [],
    brand: [],
    priceRange: [0, 100],
  })
  const [searchTerm, setSearchTerm] = useState("")
  const [cart, setCart] = useState([])
  const products = [
    {
      id: 1,
      name: "Omega-3 Fish Oil",
      description: "Supports heart and brain health",
      price: 29.99,
      category: "Supplements",
      brand: "PetWell",
      image: "/placeholder.svg",
    },
    {
      id: 2,
      name: "Glucosamine Chondroitin",
      description: "Promotes joint health and mobility",
      price: 39.99,
      category: "Supplements",
      brand: "PetCare",
      image: "/placeholder.svg",
    },
    {
      id: 3,
      name: "Probiotic Soft Chews",
      description: "Supports digestive and immune system",
      price: 24.99,
      category: "Supplements",
      brand: "PetWell",
      image: "/placeholder.svg",
    },
    {
      id: 4,
      name: "Multivitamin Tablets",
      description: "Provides essential nutrients",
      price: 19.99,
      category: "Supplements",
      brand: "PetCare",
      image: "/placeholder.svg",
    },
    {
      id: 5,
      name: "Hip & Joint Soft Chews",
      description: "Supports healthy joints and mobility",
      price: 34.99,
      category: "Supplements",
      brand: "PetWell",
      image: "/placeholder.svg",
    },
    {
      id: 6,
      name: "Calming Treats",
      description: "Helps reduce stress and anxiety",
      price: 14.99,
      category: "Supplements",
      brand: "PetCare",
      image: "/placeholder.svg",
    },
  ]
  const filteredProducts = useMemo(() => {
    return products.filter((product) => {
      if (filters.category.length > 0 && !filters.category.includes(product.category)) {
        return false
      }
      if (filters.brand.length > 0 && !filters.brand.includes(product.brand)) {
        return false
      }
      if (product.price < filters.priceRange[0] || product.price > filters.priceRange[1]) {
        return false
      }
      if (searchTerm.length > 0 && !product.name.toLowerCase().includes(searchTerm.toLowerCase())) {
        return false
      }
      return true
    })
  }, [filters, searchTerm])
  const handleFilterChange = (type, value) => {
    setFilters((prevFilters) => {
      if (type === "category") {
        return {
          ...prevFilters,
          category: prevFilters.category.includes(value)
            ? prevFilters.category.filter((item) => item !== value)
            : [...prevFilters.category, value],
        }
      } else if (type === "brand") {
        return {
          ...prevFilters,
          brand: prevFilters.brand.includes(value)
            ? prevFilters.brand.filter((item) => item !== value)
            : [...prevFilters.brand, value],
        }
      } else if (type === "priceRange") {
        return {
          ...prevFilters,
          priceRange: value,
        }
      }
      return prevFilters
    })
  }
  const handleSearchChange = (e) => {
    setSearchTerm(e.target.value)
  }
  const handleAddToCart = (product) => {
    setCart((prevCart) => [...prevCart, product])
  }
  return (
    <div className="flex flex-col h-full">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex justify-between items-center">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <PawPrintIcon className="w-6 h-6" />
            <span className="text-xl font-bold">PetSupplements</span>
          </Link>
          <nav className="hidden md:flex gap-4">
            <Link href="#" className="hover:text-accent" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="hover:text-accent" prefetch={false}>
              Products
            </Link>
            <Link href="#" className="hover:text-accent" prefetch={false}>
              About
            </Link>
            <Link href="#" className="hover:text-accent" prefetch={false}>
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            <div className="relative">
              <SearchIcon className="absolute left-2 top-1/2 transform -translate-y-1/2 text-muted-foreground" />
              <Input
                type="text"
                placeholder="Search products..."
                className="bg-background text-foreground pl-8 pr-4 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-accent focus:border-transparent"
                value={searchTerm}
                onChange={handleSearchChange}
              />
            </div>
            <Button variant="outline" className="flex items-center gap-2" onClick={() => console.log(cart)}>
              <ShoppingCartIcon className="w-5 h-5" />
              <span>Cart ({cart.length})</span>
            </Button>
          </div>
        </div>
      </header>
      <div className="flex-1 flex">
        <div className="bg-muted p-6 border-r border-muted-foreground/10 hidden md:block">
          <h3 className="text-lg font-bold mb-4">Filters</h3>
          <div className="grid gap-4">
            <div>
              <h4 className="text-sm font-semibold mb-2">Category</h4>
              <div className="grid gap-2">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={filters.category.includes("Supplements")}
                    onCheckedChange={() => handleFilterChange("category", "Supplements")}
                  />
                  Supplements
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={filters.category.includes("Treats")}
                    onCheckedChange={() => handleFilterChange("category", "Treats")}
                  />
                  Treats
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={filters.category.includes("Toys")}
                    onCheckedChange={() => handleFilterChange("category", "Toys")}
                  />
                  Toys
                </Label>
              </div>
            </div>
            <div>
              <h4 className="text-sm font-semibold mb-2">Brand</h4>
              <div className="grid gap-2">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={filters.brand.includes("PetWell")}
                    onCheckedChange={() => handleFilterChange("brand", "PetWell")}
                  />
                  PetWell
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={filters.brand.includes("PetCare")}
                    onCheckedChange={() => handleFilterChange("brand", "PetCare")}
                  />
                  PetCare
                </Label>
              </div>
            </div>
            <div>
              <h4 className="text-sm font-semibold mb-2">Price Range</h4>
              <div />
              <div className="flex justify-between text-sm text-muted-foreground">
                <span>${filters.priceRange[0]}</span>
                <span>${filters.priceRange[1]}</span>
              </div>
            </div>
          </div>
        </div>
        <div className="flex-1 p-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {filteredProducts.map((product) => (
              <div key={product.id} className="bg-background rounded-md overflow-hidden shadow-sm">
                <img
                  src="/placeholder.svg"
                  alt={product.name}
                  width={300}
                  height={200}
                  className="w-full h-48 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">{product.name}</h3>
                  <p className="text-muted-foreground mb-4">{product.description}</p>
                  <div className="flex justify-between items-center">
                    <span className="text-xl font-bold">${product.price}</span>
                    <Button variant="outline" size="sm" onClick={() => handleAddToCart(product)}>
                      Add to Cart
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

function PawPrintIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="4" r="2" />
      <circle cx="18" cy="8" r="2" />
      <circle cx="20" cy="16" r="2" />
      <path d="M9 10a5 5 0 0 1 5 5v3.5a3.5 3.5 0 0 1-6.84 1.045Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10Z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
